apiVersion: apps/v1
kind: Deployment
metadata: 
  name: site
  namespace: site
  labels: 
      name: "site"
      keel.sh/policy: force
      keel.sh/trigger: poll      
  annotations:
      keel.sh/pollSchedule: "@every 10m"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      name: site
      labels:
        app: site     
    spec:
      containers:
        - image: jwelch92/personal-site:latest # this would start repository digest checks
          imagePullPolicy: Always            
          name: site
          ports:
            - containerPort: 80   
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: site
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: site
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: site-ingress
  namespace: site
  annotations:  
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - jaredwelch.dev
      secretName: letsencrypt-prod
  rules:
  - host: jaredwelch.dev
    http:
      paths:
      - backend:
          serviceName: site
          servicePort: 80