name: Publish Docker

on:
  push: 
    branches: 
      - refs/tags/@orgname/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: jwelch92/personal-site
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: 'true'

